### ISSUE TITLE
Linux compilers are 32-bit and require i386 arch install

### ISSUE THREAD

**Issue by BrianPeek** [trapexit/3do-devkit#32]
NOTE: I'm definitely not a *nix guy, so this may all be nothing...

I found that the Linux compilers would fail to run on WSL2, GitHub Actions, and probably elsewhere with the message of `cannot execute: required file not found` due to the compilers being 32-bit builds running on a 64-bit system.  The solution I found was to install the i386 architecture stuff as follows:

```
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libc6:i386 libstdc++6:i386
```

I'd PR this into the README, but there might be a different way to accomplish this and I don't want to lead folks down a bad path...or, if this seems reasonable, I will go ahead and do so.

Thanks!

**Comment by trapexit** [comment]
You're correct. I so often need 32bit support I don't really think about it. I'll add a note in the docs.
